# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca9606b0e66f5ab441bbe71a928f465c2361566d53433de4575bd24121b538adada1c1d5bec36298a5185d54c5589bfdfc935c106ce4e52423aa648da2cb7ad4

test:
  secret_key_base: 324aef112b533f43c5f666d984755ca7b2d74cb810e63d7fcbf57c131df235e63ec441789994cc94d4eaf9d50be7fab929ada02deb1e61466ad039032a53b9bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
